### ISSUE TITLE
j-matrix does not match y-array

### ISSUE THREAD

**Issue by TravisGallo** [TravisGallo/Bat_Analyses_2018#2]
At least in one instance the j-matrix does not match the y-array. Need to figure out which one is in correct. j-matrix is coming directly from a spreadsheet that Liza created. y-matrix is coming from full detection dataset.

**Comment by mfidino** [comment]
So two things could be happening (I think). Either the y-matrix calculation was not correct or there was a data entry error in the j-matrix.

**Comment by TravisGallo** [comment]
y-matrix is calculated correctly. So, maybe be data entry error in the active dates. OR... Gabby mentioned yesterday that there was detectors that were left out and needed to be truncated for their "active dates". I wonder if the detection data is just l data lumped in, identified, and returned. Not taking into account where they truncated the active dates.

**Comment by TravisGallo** [comment]
y-matrix is not calculated correctly. Active days are actually nights, where as dates that we are using to create y-matrix are days. Need to figure out how to line up the days and nights to be correct.

**Comment by mfidino** [comment]
This is an interesting problem. I think the easiest way around this is to create a date/time column in the raw data and subtract 12 hours from it. While the actual date / times are not reflected here all of the calls that occur on one 'night' would fall into the same 'day' in the created column.

I wonder about why we have a column in our data that is called 'adjdate' which I assume stands for 'adjusted date'. Had we addressed this problem already with the historic data but not the current data?
